### ISSUE TITLE
MarketOverview component not working

### ISSUE THREAD

**Issue by ye-zaw-hein** [ehsan-shv/vue-tradingviewWidgets#13]
`[Vue warn]: Failed to resolve component: MarketOverView
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.`

**Comment by ehsan-shv** [comment]
Hi! Would you please make your issue clear and add your code?

**Comment by ye-zaw-hein** [comment]
I follow the documentation but show this warning and not working.

`
[Vue warn]: Failed to resolve component: MarketOverView If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.`

```
<template>
  <MarketOverview  />
</template>

<script>
import { MarketOverview } from 'vue-tradingview-widgets';

export default ({
  name: 'Test',
  components: {
   MarketOverview
  },
});
</script>
```

**Comment by ehsan-shv** [comment]
I checked, and it's working. Please check the [demo](https://mclq5u.csb.app/) on Codesandbox.
Notice that you have to use `Vue3` and the latest version of `vue-tradingview-widgets`
