### ISSUE TITLE
Widget color

### ISSUE THREAD

**Issue by rezaser74** [ehsan-shv/vue-tradingviewWidgets#17]
Greetings and thanks for this awesome widget.

i have a problem.
is there any way to turn chart to absolute black color?

i need to change bg to #000 as my customer said.

i may be thankful if you answer this question

**Comment by ehsan-shv** [comment]
Hi! Thanks. The Chart widget has a theme option with `light` or `dark` value. I'm not sure about changing the background to a custom color. You can check the [document](https://www.tradingview.com/widget/advanced-chart/).

**Comment by rezaser74** [comment]
i've just seen the docs before there wasn't option like that unfortunately.
by the way ty bro
