### ISSUE TITLE
Draw Horizontal lines

### ISSUE THREAD

**Issue by claumaries** [ehsan-shv/vue-tradingviewWidgets#18]
Hi, 

 Thanks for this great plugin. I was wondering if it is possible to draw custom horizontal lines on the Chart? Similar as in the below image

![BTCUSDT_2023-03-25_18-35-38](https://user-images.githubusercontent.com/32703110/227735475-b98d690b-bd72-4f70-b98b-c2f1d7cfa0e5.png)

using something like this:

```
var order = widget.chart().createOrderLine()
    .setText("Buy Line")
    .setLineLength(3) 
    .setLineStyle(0) 
    .setQuantity("221.235 USDT")
order.setPrice(7000);
```

**Comment by ehsan-shv** [comment]
Hi, Thanks. please check [here](https://www.tradingview.com/widget/advanced-chart/). I'm not sure if it's possible or not.
