### ISSUE TITLE
change symbol from code

### ISSUE THREAD

**Issue by csidi90** [ehsan-shv/vue-tradingviewWidgets#20]
Is there a way to programmatically change the symbol of the chart? I have a v-model to the chartOptions but whenever I change the symbol property, it has no effect. I could not find any solution or applySymbol function.

**Comment by ehsan-shv** [comment]
Hey! Check the [link](https://codesandbox.io/s/vue-tradingview-widgets-dynamic-props-wxxd58?file=/src/App.vue).

**Comment by csidi90** [comment]
awesome, thank you for the quick response. I am using composition API, will try it out shortly using the :key binding. I was only updating the options.symbol property and that alone had no effect.

**Comment by csidi90** [comment]
in case anyone is looking for a way using composition API, here is how I got it to work thanks to ehsan-shv options API example.

``` vue
<script setup>
import { reactive,ref, defineProps, watch } from "vue"
import { Chart } from 'vue-tradingview-widgets';

const props = defineProps(['symbol']) //gets passed to component from v-data-table on row:click
const selectedSymbol = ref("BTCUSDT") //default
const state = reactive({
  chartOptions: { "allow_symbol_change": true, symbol: selectedSymbol, autosize: false, width: "100%", height: "500", studies: ['STD;RSI'] }
});

watch(() => props.symbol, (newSymbol) => {
  selectedSymbol.value = "BINANCE:"+ newSymbol;
})
</script>
<template>
  <div>
    <h4>{{ symbol }}</h4>
    <chart :key="selectedSymbol" :options="state.chartOptions"></chart>
  </div>
</template>
```

**Comment by ehsan-shv** [comment]
Great! Thanks!

**Comment by csidi90** [comment]
I there also a way to do the same for the timeframe? Tried the same approach with the "interval" property on the chart but thats not working, unlike the symbol.

**Comment by ehsan-shv** [comment]
What do you mean by "timeframe"?

**Comment by csidi90** [comment]
the interval. Like 4H, 1H and so on. the widget has an interval property but when I bind it and change the value it does not refresh.

**Comment by ehsan-shv** [comment]
Could you please make a demo on Codesandbox?
